### ISSUE TITLE
TypeError when calling python_jaxpr_python

### ISSUE THREAD

**Issue by Lun4m** [PierrickPochelu/JaxDecompiler#1]
Hello and congrats on starting this interesting project! I encountered this bug while running the following code:
```python
import jax.numpy as jnp
from jax import value_and_grad
import decompiler 

def fun(ra, rb, r0, k):
    rab = ra - rb
    rab = jnp.sqrt(jnp.dot(rab, rab))
    return 0.5 * k * (rab - r0) ** 2

df = value_and_grad(fun)
ra = jnp.ones(3)
rb = 2 * ra
decomp, pycode = decompiler.python_jaxpr_python(df, (ra, rb, 0.5, 20.0), is_python_returned=True)
print(pycode)
```

```terminal
Traceback (most recent call last):
  File "JaxDecompiler/my_test.py", line 13, in <module>
    decomp, pycode = decompiler.python_jaxpr_python(df, (ra, rb, r0, k, box), is_python_returned=True)
  File "JaxDecompiler/decompiler.py", line 35, in python_jaxpr_python
    out = from_jaxpr_object_to_python(jaxpr_obj, **kwargs)
  File "JaxDecompiler/decompiler.py", line 22, in from_jaxpr_object_to_python
    return f, (os.linesep).join(python_lines)
TypeError: sequence item 3: expected str instance, list found
```

I guess a simple fix is to replace
https://github.com/PierrickPochelu/JaxDecompiler/blob/be3a275574bdb987e535622e027fd8737201e444/decompiler.py#L184
with
```python
        tabbed_python_lines.extend(list_of_python_lines)
```

**Comment by PierrickPochelu** [comment]
Hello, 
Thank you for your feedback. I am doing it ASAP.

**Comment by PierrickPochelu** [comment]
It is corrected. Below the associated test.

```Python
import jax.numpy as jnp
        from jax import value_and_grad
        import decompiler

        def fun(ra, rb, r0, k):
            rab = ra - rb
            rab = jnp.sqrt(jnp.dot(rab, rab))
            return 0.5 * k * (rab - r0) ** 2

        df = value_and_grad(fun)
        ra = jnp.ones(3)
        rb = 2 * ra

        x = (ra, rb, 0.5, 20.0)

        y_expected = df(*x)

        decomp, pycode = decompiler.python_jaxpr_python(df, x, is_python_returned=True)
        print(pycode)

        y = decomp(*x)

        gap = sum(array(y_expected[0]) - array(y[0]))
        self.assertAlmostEqual(0.0, gap, delta=DELTA)

        gap = sum(array(y_expected[1]) - array(y[1]))
        self.assertAlmostEqual(0.0, gap, delta=DELTA)
```

Produces this code:

```Python
import jax
from jax.numpy import *
def f(a, b, c, d):
    e = a - b
    f = dot(e, e)
    g = sqrt(f)
    h = 0.5 / g
    i = 0.5 * d
    j = array(c).astype(float32)
    k = g - j
    l = k ** 2
    m = k ** 1
    n = 2.0 * m
    o = array(i).astype(float32)
    p = o * l
    q = o * 1.0
    r = q * n
    s = r * h
    t = dot(s, e)
    u = dot(s, e)
    v = u + t
    return p, v
```



The decompilation after JIT-compilation produces this one:

```Python
import jax
from jax.numpy import *
def f(a, b, c, d):
    def local_f0(a, b, c, d):
        e = a - b
        f = dot(e, e)
        g = sqrt(f)
        h = 0.5 / g
        i = 0.5 * d
        j = array(c).astype(float32)
        k = g - j
        l = k ** 2
        m = k ** 1
        n = 2.0 * m
        o = array(i).astype(float32)
        p = o * l
        return p, o, h, e, n
    e, f, g, h, i = local_f0(a, b, c, d)
    def local_f1(a, b, c, d, e):
        f = a * e
        g = f * d
        h = g * b
        i = dot(h, c)
        j = dot(h, c)
        k = j + i
        return k
    j = local_f1(f, g, h, i, 1.0)
    return e, j
```
you can found those examples there: https://github.com/PierrickPochelu/JaxDecompiler/blob/main/test_real_life_examples.py

Please feel free to open new issues
